apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapwatchers.io
spec:
  group: configmapwatchers.io
  names:
    kind: ConfigMapWatcher
    listKind: ConfigMapWatcherList
    plural: configmapwatchers
    singular: configmapwatcher
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                configMapName:
                  type: string
                deploymentName:
                  type: string
