apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;
            server_name localhost;

            location / {
                default_type text/plain;
                return 200 "ConfigMap Loaded Successfully!\n";
            }
        }
    }
