apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-watcher-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: ["configmapwatchers.io"]
    resources: ["configmapwatchers"]
    verbs: ["get", "list", "watch"]

