apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-watcher-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: configmap-watcher-sa
    namespace: default
roleRef:
  kind: Role
  name: configmap-watcher-role
  apiGroup: rbac.authorization.k8s.io
